#!/usr/bin/env bash
set -euo pipefail
check(){ local f="$1" p="$2"; if ! grep -Eq "$p" "$f"; then echo "missing pattern in $f: $p" >&2; exit 1; fi; }
absent(){ local f="$1" p="$2"; if grep -Eq "$p" "$f"; then echo "forbidden pattern in $f: $p" >&2; exit 1; fi; }
R=backend/runtime/AuthorizedCliReaderPortRuntime.cs
S=backend/schema/CliReaderPortContracts.cs
I=backend/repository/CliReaderPortRepository.cs
N=backend/repository/NpgsqlCliReaderPortRepository.cs
D=db/topology_tables.sql
T=backend/tests/Topolactor.Runtime.Tests/AuthorizedCliReaderPortRuntimeTests.cs
TODO=.agent/tasks/todo.md
check "$R" "import_structured_output"
check "$R" "assign_business_object_candidate"
check "$R" "create_draft_operation"
check "$R" "create_commit_candidate"
check "$R" "get_preview_diff"
check "$R" "manifestId is null"
check "$R" "CLI_READER_IMPORT_CANDIDATE_CREATED"
check "$R" "CLI_READER_IMPORT_BUSINESS_OBJECT_SCOPE_DENIED"
check "$R" "CLI_READER_IMPORT_ASSIGNMENT_TARGET_SCOPE_DENIED"
check "$R" "AllowedBusinessObjects"
check "$R" "AllowedAssignmentTargetScopes"
check "$R" "ssotConfirmed = false"
check "$R" "committed = false"
check "$R" "approvalUpdated = false"
check "$S" "CreateCliReaderImportCandidateCommand"
check "$I" "CreateImportCandidateAsync"
check "$N" "topology.cli_reader_import_candidates"
check "$N" "ON CONFLICT \(idempotency_key\) DO NOTHING"
check "$N" "RETURNING event_log_id"
check "$N" "runtime_audit_ref"
check "$N" "cli_mcp_import_candidate_replayed"
check "$N" "result.CandidateId"
check "$D" "CREATE TABLE IF NOT EXISTS topology.cli_reader_import_candidates"
check "$D" "candidate_kind TEXT NOT NULL CHECK"
check "$D" "status TEXT NOT NULL CHECK"
check "$D" "cli_reader_import_candidates_no_secret_payload"
check "$D" "unresolved_fields JSONB NOT NULL"
check "$D" "preview_diff JSONB NOT NULL"
check "$D" "runtime_audit_ref"
check "$D" "REFERENCES topology.runtime_event_log"
check "$D" "assigned_business_object_candidate"
check "$D" "draft_operation_id"
check "$D" "assignment_target_scope"
check "$D" "evidence_refs"
check "$D" "ADD COLUMN IF NOT EXISTS assigned_business_object_candidate"
check "db/seed_empty.sql" "allowed_business_objects"
check "db/seed_empty.sql" "allowed_assignment_target_scopes"
check "$D" "CREATE TABLE IF NOT EXISTS topology.file_artifacts"
check "$T" "Import_structured_output_fail_closes_when_required_evidence_field_missing"
check "$T" "Candidate_operations_fail_close_when_operation_required_field_missing"
check "$T" "Candidate_operations_fail_close_when_business_object_is_outside_dispatch_scope"
check "$T" "Candidate_operations_fail_close_when_assignment_target_scope_is_outside_dispatch_scope"
check "$T" "Idempotent_replay_reuses_existing_candidate_id_for_runtime_evidence"
check "$T" "Import_candidate_operations_save_evidence_only_without_commit_or_confirmation"
check "$T" "Get_preview_diff_returns_candidate_evidence_without_apply_or_approval"
check "$T" "Mutation_and_side_effect_operations_are_rejected"
check "$TODO" "cli-mcp-import-candidate-port"
check "$TODO" "import-candidate subBundle implemented evidence"
absent "$R" "ApproveExport|approval_execute|ExecuteApproval|core_api_url.*GetString|ReadString\(payload, \"user_id\"\)"
echo "cli-mcp-import-candidate-port guard passed"
