// DO NOT EDIT. This file is generated by Fresh.
// This file should be checked into version control.
// Run `deno task build` to rebuild.

import * as $$0 from "./routes/index.tsx";
import * as $$1 from "./routes/admin/index.tsx";
import * as $$2 from "./routes/admin/context-token-registry.tsx";
import * as $$2b from "./routes/admin/registry-vector-validate.tsx";
import * as $$2c from "./routes/admin/manifests.tsx";
import * as $$2d from "./routes/admin/contents.tsx";
import * as $$2e from "./routes/admin/ui-builder.tsx";
import * as $$2f from "./routes/admin/seed.tsx";
import * as $$3 from "./routes/demo.tsx";
import * as $$3b from "./routes/demo-static.tsx";
import * as $$4 from "./routes/auth.tsx";
import * as $$5 from "./routes/runtime-status.tsx";
import * as $$6 from "./routes/api/auth/login.ts";
import * as $$7 from "./routes/api/dispatch.ts";
import * as $$10 from "./islands/ContextTokenRegistryEditor.tsx";
import * as $$11 from "./islands/AuthPanel.tsx";
import * as $$12 from "./islands/OperationPanel.tsx";
import * as $$13 from "./islands/RegistryVectorValidator.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $$0,
    "./routes/admin/index.tsx": $$1,
    "./routes/admin/context-token-registry.tsx": $$2,
    "./routes/admin/registry-vector-validate.tsx": $$2b,
    "./routes/admin/manifests.tsx": $$2c,
    "./routes/admin/contents.tsx": $$2d,
    "./routes/admin/ui-builder.tsx": $$2e,
    "./routes/admin/seed.tsx": $$2f,
    "./routes/demo.tsx": $$3,
    "./routes/demo-static.tsx": $$3b,
    "./routes/auth.tsx": $$4,
    "./routes/runtime-status.tsx": $$5,
    "./routes/api/auth/login.ts": $$6,
    "./routes/api/dispatch.ts": $$7,
  },
  islands: {
    "./islands/ContextTokenRegistryEditor.tsx": $$10,
    "./islands/AuthPanel.tsx": $$11,
    "./islands/OperationPanel.tsx": $$12,
    "./islands/RegistryVectorValidator.tsx": $$13,
  },
  baseUrl: import.meta.url,
};

export default manifest;
