// DO NOT EDIT. This file is generated by Fresh.
// This file should be checked into version control.
// Run `deno task build` to rebuild.

import * as $$0 from "./routes/index.tsx";
import * as $$1 from "./routes/admin/index.tsx";
import * as $$2 from "./routes/admin/context-token-registry.tsx";
import * as $$3 from "./routes/demo.tsx";
import * as $$4 from "./routes/login.tsx";
import * as $$5 from "./routes/runtime-status.tsx";
import * as $$6 from "./routes/api/auth/login.ts";
import * as $$7 from "./routes/api/dispatch.ts";
import * as $$8 from "./routes/api/admin/context-token-registry.ts";
import * as $$9 from "./routes/api/admin/context-token-registry/[tokenId]/deprecate.ts";
import * as $$10 from "./islands/ContextTokenRegistryEditor.tsx";
import * as $$11 from "./islands/LoginPanel.tsx";
import * as $$12 from "./islands/OperationPanel.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $$0,
    "./routes/admin/index.tsx": $$1,
    "./routes/admin/context-token-registry.tsx": $$2,
    "./routes/demo.tsx": $$3,
    "./routes/login.tsx": $$4,
    "./routes/runtime-status.tsx": $$5,
    "./routes/api/auth/login.ts": $$6,
    "./routes/api/dispatch.ts": $$7,
    "./routes/api/admin/context-token-registry.ts": $$8,
    "./routes/api/admin/context-token-registry/[tokenId]/deprecate.ts": $$9,
  },
  islands: {
    "./islands/ContextTokenRegistryEditor.tsx": $$10,
    "./islands/LoginPanel.tsx": $$11,
    "./islands/OperationPanel.tsx": $$12,
  },
  baseUrl: import.meta.url,
};

export default manifest;
