import type {
  ComponentCatalogEntry,
  ComponentCatalogIdentity,
} from "./types.ts";

// UI/UX Primitive Catalog — Variety Maximization Pass
// Source SSOT: docs/design/ui-ux-primitive-catalog-ssot.yaml
// These entries are catalog-only lineup definitions (runtimeConnected: false).
// runtimeConnected:true means runtime factory/constructor reachable via registry.
// Notes field: "catalog_primitive | candidateSurface | previewOnly | #89" as applicable.
const CATALOG_SSOT = "docs/design/ui-ux-primitive-catalog-ssot.yaml";

export const COMPONENT_TEMPLATE_CATALOG_IDENTITIES: ComponentCatalogIdentity[] =
  [
    {
      componentKey: "button.primitive",
      componentKind: "action/button",
      sourcePath: "frontend/components/Button.tsx",
    },
    {
      componentKey: "input.primitive",
      componentKind: "form_input/input",
      sourcePath: "frontend/components/Input.tsx",
    },
    {
      componentKey: "table.primitive",
      componentKind: "data_display/table",
      sourcePath: "frontend/components/Table.tsx",
    },
    {
      componentKey: "box.primitive",
      componentKind: "layout/box",
      sourcePath: "frontend/components/Box.tsx",
    },
    {
      componentKey: "card.primitive",
      componentKind: "display/card",
      sourcePath: "frontend/components/Card.tsx",
    },
    {
      componentKey: "form_field.template",
      componentKind: "form_input/form_field",
      sourcePath: "frontend/components/FormField.tsx",
    },
    {
      componentKey: "select.template",
      componentKind: "form_input/select",
      sourcePath: "frontend/components/Select.tsx",
    },
    {
      componentKey: "checkbox.template",
      componentKind: "form_input/checkbox",
      sourcePath: "frontend/components/Checkbox.tsx",
    },
    {
      componentKey: "badge.template",
      componentKind: "display/badge",
      sourcePath: "frontend/components/Badge.tsx",
    },
    {
      componentKey: "status_badge.template",
      componentKind: "display/status_badge",
      sourcePath: "frontend/components/Badge.tsx",
    },
    {
      componentKey: "alert.template",
      componentKind: "display/alert",
      sourcePath: "frontend/components/Alert.tsx",
    },
    {
      componentKey: "loading_state.template",
      componentKind: "feedback/loading",
      sourcePath: "frontend/components/LoadingState.tsx",
    },
    {
      componentKey: "empty_state.template",
      componentKind: "feedback/empty",
      sourcePath: "frontend/components/EmptyState.tsx",
    },
    {
      componentKey: "error_state.template",
      componentKind: "feedback/error",
      sourcePath: "frontend/components/ErrorState.tsx",
    },
    {
      componentKey: "json_viewer.template",
      componentKind: "data_display/json",
      sourcePath: "frontend/components/JsonViewer.tsx",
    },
    {
      componentKey: "admin_page_shell.template",
      componentKind: "shell/admin_page",
      sourcePath: "frontend/components/AdminPageShell.tsx",
    },
    {
      componentKey: "admin_section.template",
      componentKind: "shell/admin_section",
      sourcePath: "frontend/components/AdminSection.tsx",
    },
    {
      componentKey: "validation_result_panel.template",
      componentKind: "validation/result",
      sourcePath: "frontend/components/ValidationResultPanel.tsx",
    },
    {
      componentKey: "textarea.template",
      componentKind: "form_input/textarea_template",
      sourcePath: "frontend/components/Textarea.tsx",
    },
    {
      componentKey: "tabs.template",
      componentKind: "disclosure/tabs",
      sourcePath: "frontend/components/Tabs.tsx",
    },
    {
      componentKey: "modal.template",
      componentKind: "disclosure/modal",
      sourcePath: "frontend/components/Modal.tsx",
    },
    {
      componentKey: "tree.template",
      componentKind: "data_display/tree",
      sourcePath: "frontend/components/Tree.tsx",
    },
    {
      componentKey: "tree_node.template",
      componentKind: "data_display/tree_node",
      sourcePath: "frontend/components/Tree.tsx",
    },
  ];

export const RUNTIME_ALIAS_CATALOG_IDENTITIES: ComponentCatalogIdentity[] = [
  {
    componentKey: "textarea.alias",
    componentKind: "form_input/textarea",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
  },
  {
    componentKey: "search_input.alias",
    componentKind: "form_input/search_input",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
  },
  {
    componentKey: "panel.alias",
    componentKind: "disclosure_structure/panel",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
  },
  {
    componentKey: "section.alias",
    componentKind: "disclosure_structure/section",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
  },
  {
    componentKey: "data_grid.alias",
    componentKind: "data_display/data_grid",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
  },
  {
    componentKey: "list.alias",
    componentKind: "data_display/list",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
  },
];

// UI/UX Primitive Catalog identities — catalog lineup definitions (no implementation yet)
// Upper SSOT: docs/design/ui-ux-primitive-catalog-ssot.yaml
export const UI_UX_PRIMITIVE_CATALOG_IDENTITIES: ComponentCatalogIdentity[] = [
  // Category A: Search / Suggest / Candidate UI
  // autocomplete_input.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // search_combobox.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // candidate_confidence_badge.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // select_import_dialog.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // Category B: Inline Edit / Preview Update / Audit UI
  // inline_editable_field.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // patch_preview_panel.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // Category C: Table / List / View Operation UI
  // Category D: Kanban / Tree / Drag-Drop / State Transition UI (#89 prerequisite)
  // kanban_board.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // Category E: Design Token / Style Token / Layout Token UI (#89 prerequisite)
  // theme_preview_panel.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // style_token_picker.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // layout_grid_editor.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // Category F: Calculation / Topology Computation UI
  // calculation_preview_panel.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // Category G: External / Helper Lookup UI
  // Category H: Safety / Inspector / Operation Guard UI
  // apply_confirm_dialog.primitive promoted to runtimeConnected:true — removed from catalog-only list
  // validation_error_panel.primitive promoted to runtimeConnected:true — removed from catalog-only list
];

export const COMPONENT_CATALOG_ENTRIES: ComponentCatalogEntry[] = [
  {
    componentKey: "button.primitive",
    componentKind: "action/button",
    sourcePath: "frontend/components/Button.tsx",
    componentFamily: "primitive",
    semanticRole: "action",
    visualRole: "button",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["emits_event", "requires_event_binding", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "input.primitive",
    componentKind: "form_input/input",
    sourcePath: "frontend/components/Input.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "controlled_value",
      "emits_event",
      "requires_event_binding",
      "accepts_design",
    ],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "table.primitive",
    componentKind: "data_display/table",
    sourcePath: "frontend/components/Table.tsx",
    componentFamily: "primitive",
    semanticRole: "data_viewer",
    visualRole: "table",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["selectable", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "box.primitive",
    componentKind: "layout/box",
    sourcePath: "frontend/components/Box.tsx",
    componentFamily: "primitive",
    semanticRole: "layout_shell",
    visualRole: "box",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "accepts_layout", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "neutral layout container — no semantic meaning; use instead of card/panel for structural placement",
  },
  {
    componentKey: "card.primitive",
    componentKind: "display/card",
    sourcePath: "frontend/components/Card.tsx",
    componentFamily: "primitive",
    semanticRole: "display",
    visualRole: "card",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "textarea.alias",
    componentKind: "form_input/textarea",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
    componentFamily: "alias",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "alias_maintained",
    capabilityTags: [
      "controlled_value",
      "emits_event",
      "requires_event_binding",
    ],
    runtimeConnected: true,
    registrationRequired: false,
    notes: "Input primitive adapter path",
  },
  {
    componentKey: "search_input.alias",
    componentKind: "form_input/search_input",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
    componentFamily: "alias",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "alias_maintained",
    capabilityTags: [
      "controlled_value",
      "emits_event",
      "requires_event_binding",
    ],
    runtimeConnected: true,
    registrationRequired: false,
    notes: "Input primitive adapter path",
  },
  {
    componentKey: "panel.alias",
    componentKind: "disclosure_structure/panel",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
    componentFamily: "alias",
    semanticRole: "layout_shell",
    visualRole: "panel",
    lifecycleStatus: "alias_maintained",
    capabilityTags: ["accepts_children", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: false,
    notes: "Card primitive adapter path",
  },
  {
    componentKey: "section.alias",
    componentKind: "disclosure_structure/section",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
    componentFamily: "alias",
    semanticRole: "layout_shell",
    visualRole: "panel",
    lifecycleStatus: "alias_maintained",
    capabilityTags: ["accepts_children", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: false,
    notes: "Card primitive adapter path",
  },
  {
    componentKey: "data_grid.alias",
    componentKind: "data_display/data_grid",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
    componentFamily: "alias",
    semanticRole: "data_viewer",
    visualRole: "table",
    lifecycleStatus: "alias_maintained",
    capabilityTags: ["selectable", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: false,
    notes: "Table primitive adapter path",
  },
  {
    componentKey: "list.alias",
    componentKind: "data_display/list",
    sourcePath: "frontend/runtime/runtimeComponentFactory.ts",
    componentFamily: "alias",
    semanticRole: "data_viewer",
    visualRole: "table",
    lifecycleStatus: "alias_maintained",
    capabilityTags: ["selectable", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: false,
    notes: "Table primitive adapter path",
  },
  {
    componentKey: "form_field.template",
    componentKind: "form_input/form_field",
    sourcePath: "frontend/components/FormField.tsx",
    componentFamily: "template",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "error_display", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "select.template",
    componentKind: "form_input/select",
    sourcePath: "frontend/components/Select.tsx",
    componentFamily: "template",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "checkbox.template",
    componentKind: "form_input/checkbox",
    sourcePath: "frontend/components/Checkbox.tsx",
    componentFamily: "template",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "badge.template",
    componentKind: "display/badge",
    sourcePath: "frontend/components/Badge.tsx",
    componentFamily: "template",
    semanticRole: "display",
    visualRole: "badge",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "status_badge.template",
    componentKind: "display/status_badge",
    sourcePath: "frontend/components/Badge.tsx",
    componentFamily: "template",
    semanticRole: "feedback",
    visualRole: "badge",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "alert.template",
    componentKind: "display/alert",
    sourcePath: "frontend/components/Alert.tsx",
    componentFamily: "template",
    semanticRole: "feedback",
    visualRole: "alert",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_design", "error_display"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "loading_state.template",
    componentKind: "feedback/loading",
    sourcePath: "frontend/components/LoadingState.tsx",
    componentFamily: "template",
    semanticRole: "feedback",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["loading_display", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "empty_state.template",
    componentKind: "feedback/empty",
    sourcePath: "frontend/components/EmptyState.tsx",
    componentFamily: "template",
    semanticRole: "feedback",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "error_state.template",
    componentKind: "feedback/error",
    sourcePath: "frontend/components/ErrorState.tsx",
    componentFamily: "template",
    semanticRole: "feedback",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["error_display", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "json_viewer.template",
    componentKind: "data_display/json",
    sourcePath: "frontend/components/JsonViewer.tsx",
    componentFamily: "template",
    semanticRole: "data_viewer",
    visualRole: "json_viewer",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_json", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "admin_page_shell.template",
    componentKind: "shell/admin_page",
    sourcePath: "frontend/components/AdminPageShell.tsx",
    componentFamily: "template",
    semanticRole: "layout_shell",
    visualRole: "page_shell",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "accepts_children",
      "accepts_actions",
      "admin_only",
      "accepts_layout",
    ],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "admin_section.template",
    componentKind: "shell/admin_section",
    sourcePath: "frontend/components/AdminSection.tsx",
    componentFamily: "template",
    semanticRole: "layout_shell",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "accepts_children",
      "accepts_actions",
      "admin_only",
      "accepts_layout",
    ],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "validation_result_panel.template",
    componentKind: "validation/result",
    sourcePath: "frontend/components/ValidationResultPanel.tsx",
    componentFamily: "template",
    semanticRole: "validation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "textarea.template",
    componentKind: "form_input/textarea_template",
    sourcePath: "frontend/components/Textarea.tsx",
    componentFamily: "template",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "tabs.template",
    componentKind: "disclosure/tabs",
    sourcePath: "frontend/components/Tabs.tsx",
    componentFamily: "template",
    semanticRole: "navigation",
    visualRole: "tabs",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["selectable", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "modal.template",
    componentKind: "disclosure/modal",
    sourcePath: "frontend/components/Modal.tsx",
    componentFamily: "template",
    semanticRole: "display",
    visualRole: "modal",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "accepts_actions", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "tree.template",
    componentKind: "data_display/tree",
    sourcePath: "frontend/components/Tree.tsx",
    componentFamily: "template",
    semanticRole: "navigation",
    visualRole: "tree",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["recursive", "selectable", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },
  {
    componentKey: "tree_node.template",
    componentKind: "data_display/tree_node",
    sourcePath: "frontend/components/Tree.tsx",
    componentFamily: "template",
    semanticRole: "data_viewer",
    visualRole: "tree",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["recursive", "selectable", "accepts_design"],
    runtimeConnected: false,
    registrationRequired: true,
  },

  // =========================================================================
  // UI/UX Primitive Catalog — Variety Maximization Pass
  // Source SSOT: docs/design/ui-ux-primitive-catalog-ssot.yaml
  // All entries below: runtimeConnected:false, registrationRequired:true (catalog-only future topology entity candidates)
  // Implementation status: catalog_definition_only (no React component yet)
  // =========================================================================

  // Category A: Search / Suggest / Candidate UI
  {
    componentKey: "autocomplete_input.primitive",
    componentKind: "search_suggest/autocomplete_input",
    sourcePath: "frontend/components/AutoCompleteInput.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true | mutation_boundary:preview_before_apply",
  },
  {
    componentKey: "suggest_input.primitive",
    componentKind: "search_suggest/suggest_input",
    sourcePath: "frontend/components/SuggestInput.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true",
  },
  {
    componentKey: "search_combobox.primitive",
    componentKind: "search_suggest/search_combobox",
    sourcePath: "frontend/components/SearchCombobox.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "controlled_value",
      "emits_event",
      "selectable",
      "accepts_design",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true",
  },
  {
    componentKey: "select_import_dialog.primitive",
    componentKind: "search_suggest/select_import_dialog",
    sourcePath: "frontend/components/SelectImportDialog.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "modal",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "selectable",
      "emits_event",
      "requires_event_binding",
      "accepts_actions",
      "admin_only",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true | mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "relation_candidate_picker.primitive",
    componentKind: "search_suggest/relation_candidate_picker",
    sourcePath: "frontend/components/RelationCandidatePicker.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["selectable", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true",
  },
  {
    componentKey: "recent_input_suggest.primitive",
    componentKind: "search_suggest/recent_input_suggest",
    sourcePath: "frontend/components/RecentInputSuggest.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true",
  },
  {
    componentKey: "duplicate_merge_candidate_panel.primitive",
    componentKind: "search_suggest/duplicate_merge_candidate_panel",
    sourcePath: "frontend/components/DuplicateMergeCandidatePanel.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "accepts_actions",
      "displays_backend_result",
      "accepts_design",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true | mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "candidate_confidence_badge.primitive",
    componentKind: "search_suggest/candidate_confidence_badge",
    sourcePath: "frontend/components/CandidateConfidenceBadge.tsx",
    componentFamily: "primitive",
    semanticRole: "display",
    visualRole: "badge",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true",
  },
  {
    componentKey: "relation_path_preview.primitive",
    componentKind: "search_suggest/relation_path_preview",
    sourcePath: "frontend/components/RelationPathPreview.tsx",
    componentFamily: "primitive",
    semanticRole: "display",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true | candidateSurface:true",
  },
  {
    componentKey: "field_resolver_inspector.primitive",
    componentKind: "search_suggest/field_resolver_inspector",
    sourcePath: "frontend/components/FieldResolverInspector.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "schema_promotion_candidate_panel.primitive",
    componentKind: "search_suggest/schema_promotion_candidate_panel",
    sourcePath: "frontend/components/SchemaPromotionCandidatePanel.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "accepts_actions",
      "admin_only",
      "displays_backend_result",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true | mutation_boundary:preview_validate_explicit_apply",
  },

  // Category B: Inline Edit / Preview Update / Audit UI
  {
    componentKey: "inline_editable_field.primitive",
    componentKind: "inline_edit/inline_editable_field",
    sourcePath: "frontend/components/InlineEditableField.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "inline_editable_jsonb_field.primitive",
    componentKind: "inline_edit/inline_editable_jsonb_field",
    sourcePath: "frontend/components/InlineEditableJsonbField.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "json_viewer",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "controlled_value",
      "emits_event",
      "displays_json",
      "accepts_design",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "patch_preview_panel.primitive",
    componentKind: "inline_edit/patch_preview_panel",
    sourcePath: "frontend/components/PatchPreviewPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "diff_strike_text.primitive",
    componentKind: "inline_edit/diff_strike_text",
    sourcePath: "frontend/components/DiffStrikeText.tsx",
    componentFamily: "primitive",
    semanticRole: "display",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "audit_diff_drawer.primitive",
    componentKind: "inline_edit/audit_diff_drawer",
    sourcePath: "frontend/components/AuditDiffDrawer.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "modal",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "displays_backend_result",
      "accepts_children",
      "accepts_design",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "optimistic_update_boundary.primitive",
    componentKind: "inline_edit/optimistic_update_boundary",
    sourcePath: "frontend/components/OptimisticUpdateBoundary.tsx",
    componentFamily: "primitive",
    semanticRole: "validation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "confirmed_update_button.primitive",
    componentKind: "inline_edit/confirmed_update_button",
    sourcePath: "frontend/components/ConfirmedUpdateButton.tsx",
    componentFamily: "primitive",
    semanticRole: "action",
    visualRole: "button",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["emits_event", "requires_event_binding", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "mutation_boundary:explicit_confirm_required",
  },
  {
    componentKey: "undo_timeline.primitive",
    componentKind: "inline_edit/undo_timeline",
    sourcePath: "frontend/components/UndoTimeline.tsx",
    componentFamily: "primitive",
    semanticRole: "navigation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["selectable", "displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true | mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "conflict_resolution_panel.primitive",
    componentKind: "inline_edit/conflict_resolution_panel",
    sourcePath: "frontend/components/ConflictResolutionPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "accepts_actions",
      "displays_backend_result",
      "admin_only",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "mutation_boundary:preview_validate_explicit_apply",
  },

  // Category C: Table / List / View Operation UI
  {
    componentKey: "faceted_filter_bar.primitive",
    componentKind: "table_op/faceted_filter_bar",
    sourcePath: "frontend/components/FacetedFilterBar.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "column_filter.primitive",
    componentKind: "table_op/column_filter",
    sourcePath: "frontend/components/ColumnFilter.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "column_visibility_editor.primitive",
    componentKind: "table_op/column_visibility_editor",
    sourcePath: "frontend/components/ColumnVisibilityEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "sort_control.primitive",
    componentKind: "table_op/sort_control",
    sourcePath: "frontend/components/SortControl.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "group_by_control.primitive",
    componentKind: "table_op/group_by_control",
    sourcePath: "frontend/components/GroupByControl.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "saved_view_selector.primitive",
    componentKind: "table_op/saved_view_selector",
    sourcePath: "frontend/components/SavedViewSelector.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["selectable", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true",
  },
  {
    componentKey: "bulk_action_panel.primitive",
    componentKind: "table_op/bulk_action_panel",
    sourcePath: "frontend/components/BulkActionPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "action",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_actions", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "virtualized_data_table.primitive",
    componentKind: "table_op/virtualized_data_table",
    sourcePath: "frontend/components/VirtualizedDataTable.tsx",
    componentFamily: "primitive",
    semanticRole: "data_viewer",
    visualRole: "table",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["selectable", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "row_detail_drawer.primitive",
    componentKind: "table_op/row_detail_drawer",
    sourcePath: "frontend/components/RowDetailDrawer.tsx",
    componentFamily: "primitive",
    semanticRole: "display",
    visualRole: "modal",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "pagination_control.primitive",
    componentKind: "table_op/pagination_control",
    sourcePath: "frontend/components/PaginationControl.tsx",
    componentFamily: "primitive",
    semanticRole: "navigation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "export_candidate_panel.primitive",
    componentKind: "table_op/export_candidate_panel",
    sourcePath: "frontend/components/ExportCandidatePanel.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_actions", "admin_only"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true | mutation_boundary:preview_validate_explicit_apply",
  },

  // Category D: Kanban / Tree / Drag-Drop / State Transition UI (#89 prerequisite)
  {
    componentKey: "kanban_board.primitive",
    componentKind: "kanban_drag/kanban_board",
    sourcePath: "frontend/components/KanbanBoard.tsx",
    componentFamily: "primitive",
    semanticRole: "data_viewer",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "selectable", "accepts_layout"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 prerequisite",
  },
  {
    componentKey: "drag_drop_state_transition.primitive",
    componentKind: "kanban_drag/drag_drop_state_transition",
    sourcePath: "frontend/components/DragDropStateTransition.tsx",
    componentFamily: "primitive",
    semanticRole: "action",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["emits_event"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "mutation_boundary:preview_validate_explicit_apply | #89 prerequisite",
  },
  {
    componentKey: "drag_sort_list.primitive",
    componentKind: "kanban_drag/drag_sort_list",
    sourcePath: "frontend/components/DragSortList.tsx",
    componentFamily: "primitive",
    semanticRole: "data_viewer",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "accepts_children",
      "selectable",
      "emits_event",
      "accepts_layout",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "relation_drop_zone.primitive",
    componentKind: "kanban_drag/relation_drop_zone",
    sourcePath: "frontend/components/RelationDropZone.tsx",
    componentFamily: "primitive",
    semanticRole: "layout_shell",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "emits_event", "accepts_layout"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true | #89 prerequisite",
  },
  {
    componentKey: "tree_reorder_drop_zone.primitive",
    componentKind: "kanban_drag/tree_reorder_drop_zone",
    sourcePath: "frontend/components/TreeReorderDropZone.tsx",
    componentFamily: "primitive",
    semanticRole: "layout_shell",
    visualRole: "tree",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "emits_event", "accepts_layout"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "layout_drop_zone.primitive",
    componentKind: "kanban_drag/layout_drop_zone",
    sourcePath: "frontend/components/LayoutDropZone.tsx",
    componentFamily: "primitive",
    semanticRole: "layout_shell",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_children", "accepts_layout", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 layout builder placement surface",
  },
  {
    componentKey: "component_placement_handle.primitive",
    componentKind: "kanban_drag/component_placement_handle",
    sourcePath: "frontend/components/ComponentPlacementHandle.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["admin_only", "accepts_layout"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 layout builder placement handle",
  },
  {
    componentKey: "snap_grid_overlay.primitive",
    componentKind: "kanban_drag/snap_grid_overlay",
    sourcePath: "frontend/components/SnapGridOverlay.tsx",
    componentFamily: "primitive",
    semanticRole: "layout_shell",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_layout", "admin_only"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 layout builder grid reference",
  },
  {
    componentKey: "state_transition_arrow.primitive",
    componentKind: "kanban_drag/state_transition_arrow",
    sourcePath: "frontend/components/StateTransitionArrow.tsx",
    componentFamily: "primitive",
    semanticRole: "display",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "",
  },
  {
    componentKey: "slot_placeholder_panel.primitive",
    componentKind: "kanban_drag/slot_placeholder_panel",
    sourcePath: "frontend/components/SlotPlaceholderPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "layout_shell",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_layout", "admin_only"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 layout builder slot indicator",
  },

  // Category E: Design Token / Style Token / Layout Token UI (#89 prerequisite)
  {
    componentKey: "font_token_editor.primitive",
    componentKind: "design_token/font_token_editor",
    sourcePath: "frontend/components/FontTokenEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 token management | hardcode prohibited",
  },
  {
    componentKey: "background_color_editor.primitive",
    componentKind: "design_token/background_color_editor",
    sourcePath: "frontend/components/BackgroundColorEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 token management",
  },
  {
    componentKey: "text_color_editor.primitive",
    componentKind: "design_token/text_color_editor",
    sourcePath: "frontend/components/TextColorEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 token management",
  },
  {
    componentKey: "spacing_token_editor.primitive",
    componentKind: "design_token/spacing_token_editor",
    sourcePath: "frontend/components/SpacingTokenEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 token management",
  },
  {
    componentKey: "border_radius_editor.primitive",
    componentKind: "design_token/border_radius_editor",
    sourcePath: "frontend/components/BorderRadiusEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 token management",
  },
  {
    componentKey: "theme_preview_panel.primitive",
    componentKind: "design_token/theme_preview_panel",
    sourcePath: "frontend/components/ThemePreviewPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "display",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true | #89 token management",
  },
  {
    componentKey: "layout_grid_editor.primitive",
    componentKind: "design_token/layout_grid_editor",
    sourcePath: "frontend/components/LayoutGridEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "controlled_value",
      "emits_event",
      "admin_only",
      "accepts_layout",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 layout grid configuration",
  },
  {
    componentKey: "responsive_rule_editor.primitive",
    componentKind: "design_token/responsive_rule_editor",
    sourcePath: "frontend/components/ResponsiveRuleEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "controlled_value",
      "emits_event",
      "admin_only",
      "accepts_layout",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 responsive rule management",
  },
  {
    componentKey: "style_token_picker.primitive",
    componentKind: "design_token/style_token_picker",
    sourcePath: "frontend/components/StyleTokenPicker.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["selectable", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true | #89 token picker",
  },
  {
    componentKey: "css_variable_preview.primitive",
    componentKind: "design_token/css_variable_preview",
    sourcePath: "frontend/components/CssVariablePreview.tsx",
    componentFamily: "primitive",
    semanticRole: "display",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true | #89 token preview",
  },
  {
    componentKey: "shadow_token_editor.primitive",
    componentKind: "design_token/shadow_token_editor",
    sourcePath: "frontend/components/ShadowTokenEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 token management",
  },
  {
    componentKey: "animation_token_editor.primitive",
    componentKind: "design_token/animation_token_editor",
    sourcePath: "frontend/components/AnimationTokenEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "#89 token management",
  },

  // Category F: Calculation / Topology Computation UI
  {
    componentKey: "calculation_preview_panel.primitive",
    componentKind: "calc_topology/calculation_preview_panel",
    sourcePath: "frontend/components/CalculationPreviewPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true | candidateSurface:true",
  },
  {
    componentKey: "formula_builder.primitive",
    componentKind: "calc_topology/formula_builder",
    sourcePath: "frontend/components/FormulaBuilder.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "computed_field_preview.primitive",
    componentKind: "calc_topology/computed_field_preview",
    sourcePath: "frontend/components/ComputedFieldPreview.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "relation_score_preview.primitive",
    componentKind: "calc_topology/relation_score_preview",
    sourcePath: "frontend/components/RelationScorePreview.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true | candidateSurface:true",
  },
  {
    componentKey: "hub_statistics_panel.primitive",
    componentKind: "calc_topology/hub_statistics_panel",
    sourcePath: "frontend/components/HubStatisticsPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "data_viewer",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "aggregation_preview_table.primitive",
    componentKind: "calc_topology/aggregation_preview_table",
    sourcePath: "frontend/components/AggregationPreviewTable.tsx",
    componentFamily: "primitive",
    semanticRole: "data_viewer",
    visualRole: "table",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "cross_entity_calculation_panel.primitive",
    componentKind: "calc_topology/cross_entity_calculation_panel",
    sourcePath: "frontend/components/CrossEntityCalculationPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true | candidateSurface:true",
  },
  {
    componentKey: "topology_distance_preview.primitive",
    componentKind: "calc_topology/topology_distance_preview",
    sourcePath: "frontend/components/TopologyDistancePreview.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "route_cost_preview.primitive",
    componentKind: "calc_topology/route_cost_preview",
    sourcePath: "frontend/components/RouteCostPreview.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true | candidateSurface:true",
  },
  {
    componentKey: "attention_weight_preview.primitive",
    componentKind: "calc_topology/attention_weight_preview",
    sourcePath: "frontend/components/AttentionWeightPreview.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "previewOnly:true | candidateSurface:true | sql_attention_boundary:observation_surface_only",
  },
  {
    componentKey: "cooccurrence_matrix_preview.primitive",
    componentKind: "calc_topology/cooccurrence_matrix_preview",
    sourcePath: "frontend/components/CooccurrenceMatrixPreview.tsx",
    componentFamily: "primitive",
    semanticRole: "data_viewer",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true | candidateSurface:true",
  },
  {
    componentKey: "rank_score_preview.primitive",
    componentKind: "calc_topology/rank_score_preview",
    sourcePath: "frontend/components/RankScorePreview.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "previewOnly:true | candidateSurface:true | sql_attention_boundary:recommendation_candidate_surface_only",
  },

  // Category G: External / Helper Lookup UI
  {
    componentKey: "kana_assist_input.primitive",
    componentKind: "external_lookup/kana_assist_input",
    sourcePath: "frontend/components/KanaAssistInput.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "candidateSurface:true | external_lookup:kana_assist",
  },
  {
    componentKey: "postal_address_lookup.primitive",
    componentKind: "external_lookup/postal_address_lookup",
    sourcePath: "frontend/components/PostalAddressLookup.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "candidateSurface:true | external_lookup:postal_address | not_canonical_SSOT",
  },
  {
    componentKey: "address_postal_lookup.primitive",
    componentKind: "external_lookup/address_postal_lookup",
    sourcePath: "frontend/components/AddressPostalLookup.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "candidateSurface:true | external_lookup:address_postal | not_canonical_SSOT",
  },
  {
    componentKey: "tel_address_candidate_lookup.primitive",
    componentKind: "external_lookup/tel_address_candidate_lookup",
    sourcePath: "frontend/components/TelAddressCandidateLookup.tsx",
    componentFamily: "primitive",
    semanticRole: "input",
    visualRole: "field",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["controlled_value", "emits_event", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "candidateSurface:true | external_lookup:tel_address | restriction:internal_master_only",
  },
  {
    componentKey: "normalize_address_candidate.primitive",
    componentKind: "external_lookup/normalize_address_candidate",
    sourcePath: "frontend/components/NormalizeAddressCandidate.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "previewOnly:true | candidateSurface:true | not_canonical_SSOT",
  },
  {
    componentKey: "lookup_candidate_confirm_panel.primitive",
    componentKind: "external_lookup/lookup_candidate_confirm_panel",
    sourcePath: "frontend/components/LookupCandidateConfirmPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "validation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_actions", "displays_backend_result"],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "candidateSurface:true | mutation_boundary:explicit_confirm_required",
  },
  {
    componentKey: "bulk_import_candidate_panel.primitive",
    componentKind: "external_lookup/bulk_import_candidate_panel",
    sourcePath: "frontend/components/BulkImportCandidatePanel.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "accepts_actions",
      "admin_only",
      "displays_backend_result",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "candidateSurface:true | mutation_boundary:preview_validate_explicit_apply",
  },

  // Category H: Safety / Inspector / Operation Guard UI
  {
    componentKey: "command_palette.primitive",
    componentKind: "safety_guard/command_palette",
    sourcePath: "frontend/components/CommandPalette.tsx",
    componentFamily: "primitive",
    semanticRole: "navigation",
    visualRole: "modal",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_actions", "admin_only"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "mutation_boundary:dry_run_before_apply",
  },
  {
    componentKey: "empty_state_action_panel.primitive",
    componentKind: "safety_guard/empty_state_action_panel",
    sourcePath: "frontend/components/EmptyStateActionPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "feedback",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_actions", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "operation_guard_banner.primitive",
    componentKind: "safety_guard/operation_guard_banner",
    sourcePath: "frontend/components/OperationGuardBanner.tsx",
    componentFamily: "primitive",
    semanticRole: "feedback",
    visualRole: "alert",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "mutation_boundary_inspector.primitive",
    componentKind: "safety_guard/mutation_boundary_inspector",
    sourcePath: "frontend/components/MutationBoundaryInspector.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "permission_hint_panel.primitive",
    componentKind: "safety_guard/permission_hint_panel",
    sourcePath: "frontend/components/PermissionHintPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "feedback",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
  },
  {
    componentKey: "dry_run_result_panel.primitive",
    componentKind: "safety_guard/dry_run_result_panel",
    sourcePath: "frontend/components/DryRunResultPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "apply_confirm_dialog.primitive",
    componentKind: "safety_guard/apply_confirm_dialog",
    sourcePath: "frontend/components/ApplyConfirmDialog.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "modal",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["accepts_actions", "admin_only"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "mutation_boundary:explicit_confirm_required",
  },
  {
    componentKey: "rollback_candidate_panel.primitive",
    componentKind: "safety_guard/rollback_candidate_panel",
    sourcePath: "frontend/components/RollbackCandidatePanel.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "accepts_actions",
      "admin_only",
      "displays_backend_result",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "candidateSurface:true | mutation_boundary:preview_validate_explicit_apply",
  },
  {
    componentKey: "operation_audit_log_panel.primitive",
    componentKind: "safety_guard/operation_audit_log_panel",
    sourcePath: "frontend/components/OperationAuditLogPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "diagnostic",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["displays_backend_result", "accepts_design"],
    runtimeConnected: true,
    registrationRequired: true,
    notes: "previewOnly:true",
  },
  {
    componentKey: "validation_error_panel.primitive",
    componentKind: "safety_guard/validation_error_panel",
    sourcePath: "frontend/components/ValidationErrorPanel.tsx",
    componentFamily: "primitive",
    semanticRole: "validation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "error_display",
      "displays_backend_result",
      "accepts_design",
    ],
    runtimeConnected: true,
    registrationRequired: true,
  },

  // Category G (Document Canvas): Document Canvas / Template Projection UI
  // Upper SSOT: docs/design/ui-ux-primitive-catalog-ssot.yaml (category_g_document_canvas)
  // runtimeConnected:true — factory/projectionConstructor wired; runtime projection surface.
  {
    componentKey: "document_canvas_template_editor.primitive",
    componentKind: "document_canvas/document_canvas_template_editor",
    sourcePath: "frontend/components/DocumentCanvasTemplateEditor.tsx",
    componentFamily: "primitive",
    semanticRole: "admin_operation",
    visualRole: "canvas",
    lifecycleStatus: "code_only_drift",
    capabilityTags: [
      "accepts_design",
      "accepts_layout",
      "field_binding",
      "preview_surface",
      "export_snapshot",
      "admin_only",
    ],
    runtimeConnected: true,
    registrationRequired: true,
    notes:
      "projection_scaffold_only | background_reference_alignment | not_report_layout_engine",
  },
];

// UI/UX primitive catalog identities are definition-only until executable component slice is implemented.
// sourcePath: CATALOG_SSOT means the primitive exists in SSOT/todo planning, not as executable component path yet.
const UI_UX_PRIMITIVE_CATALOG_IDENTITY_LEGACY_DRAFT:
  ComponentCatalogIdentity[] = [
    {
      componentKey: "AutoCompleteInput",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "SearchCombobox",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "CandidateConfidenceBadge",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "InlineEditableField",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "PatchPreviewPanel",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "ApplyConfirmDialog",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "FacetedFilterBar",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "VirtualizedDataTable",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "LayoutDropZone",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "ComponentPlacementHandle",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "SnapGridOverlay",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "StyleTokenPicker",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "ThemePreviewPanel",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "DryRunResultPanel",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
    {
      componentKey: "ValidationErrorPanel",
      componentKind: "ui_ux/primitive",
      sourcePath: "CATALOG_SSOT",
    },
  ];

export const UI_UX_PRIMITIVE_CATALOG_DEFINITION_ENTRIES:
  ComponentCatalogEntry[] = UI_UX_PRIMITIVE_CATALOG_IDENTITIES.map((
    identity,
  ) => ({
    componentKey: identity.componentKey,
    componentKind: identity.componentKind,
    sourcePath: identity.sourcePath,
    componentFamily: "template",
    semanticRole: "admin_operation",
    visualRole: "panel",
    lifecycleStatus: "code_only_drift",
    capabilityTags: ["admin_only"],
    runtimeConnected: false,
    registrationRequired: true,
    notes: "catalog_definition_only",
  }));
